ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "passwordHash" TEXT;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "role" TEXT NOT NULL DEFAULT 'family';
